version: '0.1'
services:
  app:
    container_name: board_app
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - board-postgres          # Uncomment this when using postgres.


  board-postgres:
    image: postgres:latest
    container_name: board_db_postgres
    environment:
      - POSTGRES_USER=boardking
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=board
#      - DATABASE_HOST=board_db_postgres
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: [ "-path", "migrations", "-database",  "postgres://boardking:test@board-postgres:5432/board?sslmode=disable", "up" ]
    links:
      - board-postgres
    depends_on:
      - board-postgres


volumes:
  api:
  database_postgres:                  # Uncomment this when using postgres.